imports:
  - { resource: parameters.yml }
  - { resource: security.yml }
  - { resource: services.yml }

monolog:
  channels: ['user_access']
  handlers:
    user_access:
      level:    error
      type:     stream
      path:     '%kernel.logs_dir%/user_access.log'
      channels: [user_access]

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  locale: fr

# Symfony Configuration
framework:
  secret:          "%secret%"
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  form:            ~
  csrf_protection: ~
  validation:      { enable_annotations: true }
  templating:
    engines: ['twig']
  default_locale:  "%locale%"
  trusted_hosts:   ~
  trusted_proxies: ~
  session:
    handler_id:  ~
    name: GPSESSID
  fragments:       ~
  http_method_override: true

# Twig Configuration
twig:
  debug:            "%kernel.debug%"
  strict_variables: "%kernel.debug%"
  globals:
    application_name: "%application_name%"
    support_address: "%support_address%"

# Doctrine Configuration
doctrine:
  dbal:
    charset:  UTF8
    server_version: 5.6
    mapping_types:
      enum: string
  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true

# Doctrine Migrations Configuration
doctrine_migrations:
  dir_name: "%kernel.root_dir%/DoctrineMigrations"
  namespace: Application\Migrations
  table_name: migration_versions
  name: Application Migrations

# Swiftmailer Configuration
swiftmailer:
  transport:  "%mailer_transport%"
  host:       "%mailer_host%"
  port:       "%mailer_port%"
  username:   "%mailer_user%"
  password:   "%mailer_password%"
  spool:      { type: memory }

# FosUser Bundle Configuration
fos_user:
  db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
  firewall_name: main
  user_class: GP\CoreBundle\Entity\User
  from_email:
    address:  "%notification_sender_mail%"
    sender_name: "%application_name% Project Team"
  service:
    mailer: fos_user.mailer.twig_swift
  resetting:
    email:
      template: Email/password_resetting.email.twig
  registration:
    form:
      type: GP\CoreBundle\Form\Type\RegistrationFormType
  profile:
    form:
      type: app_user_profile_edit

# KnpPaginator Configuration
knp_paginator:
  page_range: "%item_per_page%"
  template:
    pagination: :Pagination:sliding.html.twig
    sortable: :Pagination:sortable_link.html.twig
