security:

  encoders:
    Symfony\Component\Security\Core\User\User:
      algorithm: sha512
      encode_as_base64: false
      iterations: 1
    GyverBundle\Entity\User: sha512

  role_hierarchy:
    ROLE_ADMIN: ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main_provider:
      entity:
        class: GyverBundle:User
        property: username
    in_memory:
      memory:
        users:
          user:  { password: b109f3bbbc244eb82441917ed06d618b9008dd09b3befd1b5e07394c706a8bb980b1d7785e5976ec049b46df5f1326af5a2ea6d103fd07c95385ffab0cacbc86, roles: [ 'ROLE_USER' ] }
          admin: { password: b109f3bbbc244eb82441917ed06d618b9008dd09b3befd1b5e07394c706a8bb980b1d7785e5976ec049b46df5f1326af5a2ea6d103fd07c95385ffab0cacbc86 , roles: [ 'ROLE_ADMIN' ] }
          super_admin: { password: b109f3bbbc244eb82441917ed06d618b9008dd09b3befd1b5e07394c706a8bb980b1d7785e5976ec049b46df5f1326af5a2ea6d103fd07c95385ffab0cacbc86 , roles: [ 'ROLE_SUPER_ADMIN' ] }

  firewalls:
    dev:
      pattern: (_(profiler|wdt)|css|images|js)/
      security: false

    main:
      pattern: ^/
      anonymous: true
      provider: in_memory
      form_login:
        login_path: login
        check_path: login_check
      logout:
        path: logout
        target: /login
