security:

  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    GyverBundle\Entity\User: plaintext

  role_hierarchy:
    ROLE_ADMIN: ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main_provider:
      entity:
        class: GyverBundle:User
        property: username

    in_memory:
      memory:
        users:
          user: { password: userpass, roles: [ 'ROLE_USER' ] }
          admin: { password: userpass, roles: [ 'ROLE_USER' ] }

  firewalls:
    dev:
      pattern: (_(profiler|wdt)|css|images|js)/
      security: false

    main:
      pattern: ^/
      anonymous: true
      provider: main_provider
      form_login:
        login_path: login
        check_path: login_check
      logout:
        path: logout
        target: /login