# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.profile.edit:
        class: GP\UserBundle\Form\Type\EditUserFormType
        tags:
          - { name: form.type, alias: app_user_profile_edit }

    # Mailer service
    gp.core_bundle.mailing_service:
        class: GP\CoreBundle\Services\MailingService
        arguments: [@Mailer, @Templating, %notification_sender_mail%, %notification_bcc_mail%, %kernel.environment%]

    app.form.registration:
        class: GP\CoreBundle\Form\Type\RegistrationFormType
        tags:
            - { name: "form.type", alias: "app_user_registration" }

    app.form.invitation:
        class: GP\CoreBundle\Form\Type\InvitationFormType
        arguments: ['@app.form.data_transformer.invitation']
        tags:
            - { name: "form.type", alias: "app_invitation_type" }

    app.form.data_transformer.invitation:
        class: GP\CoreBundle\Form\DataTransformer\InvitationToCodeTransformer
        arguments: ['@doctrine.orm.entity_manager']
        public: false
