# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.profile.edit:
        class: GP\UserBundle\Form\Type\EditUserFormType
        tags:
          - { name: form.type, alias: app_user_profile_edit }

    # Mailer service
    gp.core_bundle.mailing_service:
        class: GP\CoreBundle\Services\MailingService
        arguments: [@Mailer, @Templating, %notification_sender_mail%, %kernel.environment%]
