# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.profile.edit:
        class: GP\UserBundle\Form\Type\EditUserFormType
        tags:
          - { name: form.type, alias: app_user_profile_edit }

    # Mailer service
    gp.core_bundle.mailing_service:
        class: GP\CoreBundle\Services\MailingService
        arguments: ['@mailer', '@templating', '%notification_sender_mail%', '%notification_bcc_mail%', '%kernel.environment%', '%application_name%' ]

    gp.core_bundle.project_validator:
        class: GP\CoreBundle\Validator\Constraints\ProjectValidator
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: validator.constraint_validator, alias: project_validator }

    # Required by FOS to enable user invitation system
    app.form.registration:
        class: GP\CoreBundle\Form\Type\RegistrationFormType
        tags:
            - { name: "form.type", alias: "app_user_registration" }

    app.form.invitation:
        class: GP\CoreBundle\Form\Type\InvitationFormType
        arguments: ['@app.form.data_transformer.invitation']
        tags:
            - { name: "form.type", alias: "app_invitation_type" }

    app.form.data_transformer.invitation:
        class: GP\CoreBundle\Form\DataTransformer\InvitationToCodeTransformer
        arguments: ['@doctrine.orm.entity_manager']
        public: false

    # GyverProject Twig extension
    app.twig_extension.gyver_project:
        class: 'GP\CoreBundle\Twig\GyverProjectExtension'
        public: false
        tags:
            - { name: twig.extension }

    # Assets revision Twig extension
    app.twig_extension.asset_version:
        class: 'GP\CoreBundle\Twig\AssetVersionExtension'
        arguments: [ '%kernel.root_dir%' ]
        public: false
        tags:
            - { name: twig.extension }
