GP\CoreBundle\Entity\Project:
    project (template):
        name: Project Sample
        description: project description sample
        status: 20
        creationDate: <dateTime("2015-01-01 12:00:00")>
        beginDate: <dateTime("2015-01-01 23:59:59")>
        plannedEndDate: <dateTime("2025-01-01 23:59:59")>

    testproject (extends project):
        name: test new project
        description: test project
        plannedEndDate: <dateTime("2020-01-01 20:00:00")>

    gyver (extends project):
        name: Projet Gyver
        description: Gyver project Yeah !
        status: 40
        plannedEndDate: <dateTime("2020-01-01 20:00:00")>

    iris (extends project):
        name: Projet Iris
        description: Iris project Yeah !
        status: 40
        plannedEndDate: <dateTime("2020-01-01 20:00:00")>

    kiss (extends project):
        name: Projet Kiss
        description: Kiss project Yeah !
        status: 50
        plannedEndDate: <dateTime("2020-01-01 20:00:00")>

    solid (extends project):
        name: Projet Solid
        description: Solid project Yeah !
        status: 50
        plannedEndDate: <dateTime("2020-01-01 20:00:00")>

    test1 (extends project):
        name: Projet test1
        description: test1 project description ...
        status: 40
        plannedEndDate: <dateTime("2020-01-01 20:00:00")>

    test2 (extends project):
        name: Projet test2
        description: test2 project description ...
        status: 30
        plannedEndDate: <dateTime("2020-01-01 20:00:00")>

    test3 (extends project):
        name: Projet test3
        description: test3 project description ...
        status: 60
        plannedEndDate: <dateTime("2020-01-01 20:00:00")>

    test4 (extends project):
        name: Projet test4
        description: test4 project description ...
        status: 0
        plannedEndDate: <dateTime("2020-01-01 20:00:00")>

    test5 (extends project):
        name: Projet test5
        description: test5 project description ...
        status: 0
        plannedEndDate: <dateTime("2020-01-01 20:00:00")>
