<?php

namespace GP\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use GP\CoreBundle\Entity\User;

/**
 * Company Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{

    /**
     * Get all companies attached to the given user
     *
     * @param User $user
     * @param null $limit
     * @return array
     */
    public function findUserCompanies(User $user, $limit = null)
    {
        $companies = $this->createQueryBuilder('c')
            ->select('c')
            ->join('c.users', 'u')
            ->where('u = :user')
            ->setParameter('user', $user->getId())
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult()
        ;

        return $companies;
    }
}
