<?php

namespace GP\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Company Role Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRoleRepository extends EntityRepository
{
}
