<?php

namespace GP\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Company Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
}
