<?php

namespace GP\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRoleRepository extends EntityRepository
{
}
