<?php

namespace GP\CompanyBundle\Entity;

/**
 * CompanyRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
